[env:esp32-s3-devkitc-1]
platform = espressif32@7.0.1
board = esp32-s3-devkitc-1
framework = espidf

upload_port = COM3
monitor_port = COM3
monitor_speed = 115200

board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.flash_mode = dio
board_build.f_flash = 40000000L
